#FROM binhex/arch-int-vpn:2025100101
FROM binhex/arch-int-vpn:latest

ENV NZBGET_VERSION=26.2-testing-20260501
ENV NZBGET_VERSION_DIR=testing
ENV NZBGET_SHA256=5f6e5b221fafc820be09424164de030924338a784e3501066602cb2d581197be
ENV NZBGET_CACERT_SHA256=491eedffee3a7abc1967031205d5c31c0d8de88783360b562e847b57ab94d50f

# additional files
##################

# add supervisor conf file for app
ADD build/*.conf /etc/supervisor/conf.d/

# add bash scripts to install app
ADD build/root/*.sh /root/

# add run bash scripts
ADD run/root/*.sh /root/

# add run bash scripts
ADD run/nobody/*.sh /home/nobody/

# install app
#############

# make executable and run bash scripts to install app
RUN chmod +x /root/*.sh /home/nobody/*.sh && /bin/bash /root/install.sh

# docker settings
#################

# map /config to host defined config path (used to store configuration from app)
VOLUME /config

# map /data to host defined data path (used to store data from app)
VOLUME /data

# expose port for http
EXPOSE 6789

# set permissions
#################

# run script to set uid, gid and permissions
CMD ["/bin/bash", "/usr/bin/init.sh"]
